name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: vincentlim27
          password: Vincent27

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64 \
          --build-arg PORT=3000 \
          --build-arg DB_URL="host=localhost user=postgres password=Vincent27 dbname=localArtisans port=5432 sslmode=disable" \
          --build-arg TIMEOUT="3s" \
          -t vincentlim27/localartisansv1 . --push

      - name: Run Docker container
        run: |
          docker-compose up --build -d
